let FLAGS = [
    { flag: "STAFF", bitwise: 1 << 0 },
    { flag: "PARTNER", bitwise: 1 << 1 },
    { flag: "HYPESQUAD", bitwise: 1 << 2 },
    { flag: "BUG_HUNTER_LEVEL_1", bitwise: 1 << 3 },
    { flag: "MFA_SMS", bitwise: 1 << 4 },
    { flag: "PREMIUM_PROMO_DISMISSED", bitwise: 1 << 5 },
    { flag: "HYPESQUAD_BRAVERY", bitwise: 1 << 6 },
    { flag: "HYPESQUAD_BRILLIANCE", bitwise: 1 << 7 },
    { flag: "HYPESQUAD_BALANCE", bitwise: 1 << 8 },
    { flag: "PREMIUM_EARLY_SUPPORTER", bitwise: 1 << 9 },
    { flag: "TEAM_PSEUDO_USER", bitwise: 1 << 10 },
    { flag: "INTERNAL_APPLICATION", bitwise: 1 << 11 },
    { flag: "SYSTEM", bitwise: 1 << 12 },
    { flag: "HAS_UNREAD_URGENT_MESSAGES", bitwise: 1 << 13 },
    { flag: "BUG_HUNTER_LEVEL_2", bitwise: 1 << 14 },
    { flag: "UNDERAGE_DELETED", bitwise: 1 << 15 },
    { flag: "VERIFIED_BOT", bitwise: 1 << 16 },
    { flag: "VERIFIED_DEVELOPER", bitwise: 1 << 17 },
    { flag: "CERTIFIED_MODERATOR", bitwise: 1 << 18 },
    { flag: "BOT_HTTP_INTERACTIONS", bitwise: 1 << 19 },
    { flag: "SPAMMER", bitwise: 1 << 20 },
    { flag: "DISABLE_PREMIUM", bitwise: 1 << 21 },
    { flag: "ACTIVE_DEVELOPER", bitwise: 1 << 22 },
    { flag: "PROVISIONAL_ACCOUNT", bitwise: 1 << 23 },
    { flag: "HIGH_GLOBAL_RATE_LIMIT", bitwise: 1 << 33 },
    { flag: "DELETED", bitwise: 1 << 34 },
    { flag: "DISABLED_SUSPICIOUS_ACTIVITY", bitwise: 1 << 35 },
    { flag: "SELF_DELETED", bitwise: 1 << 36 },
    { flag: "PREMIUM_DISCRIMINATOR", bitwise: 1 << 37 },
    { flag: "USED_DESKTOP_CLIENT", bitwise: 1 << 38 },
    { flag: "USED_WEB_CLIENT", bitwise: 1 << 39 },
    { flag: "USED_MOBILE_CLIENT", bitwise: 1 << 40 },
    { flag: "DISABLED", bitwise: 1 << 41 },
    { flag: "QUARANTINED", bitwise: 1 << 44 },
    { flag: "COLLABORATOR", bitwise: 1 << 50 },
    { flag: "RESTRICTED_COLLABORATOR", bitwise: 1 << 51 }
];

export default FLAGS;
